import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
const root=path.dirname(fileURLToPath(import.meta.url));
const config=JSON.parse(await readFile(path.join(root,'site.json'),'utf8'));
const articles=JSON.parse(await readFile(path.join(root,'articles.json'),'utf8'));
const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const disclosure='As an Amazon Associate I earn from qualifying purchases.';
const brand='Linen &amp; Form';
const logo='<span>Linen <em>&amp;</em> Form</span>';
const nav='<a href="/guides/">The guides</a><a href="/guides/neutral-living-room-essentials/">Living</a><a href="/guides/affordable-bedroom-upgrades/">Bedroom</a><a href="/guides/small-apartment-organization/">Organization</a><a class="nav-edit" href="/guides/home-finds-under-100/">The under-$100 edit</a>';
const email=config.contactEmail;
if(email&&!/^[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+$/.test(email))throw Error('Use a valid contactEmail in site.json');
let origin='';
if(config.url){const u=new URL(config.url);if(u.protocol!=='https:')throw Error('site.url must use HTTPS');origin=u.origin;}
const images={living:'A warm neutral living room with an ivory sofa, wood coffee table, and shaded lamp',bedroom:'A bedroom with layered ivory bedding, wood bedside tables, and softly shaded lamps',kitchen:'A cream kitchen with wood surfaces, ceramic accessories, and organized open shelves'};
const image=(name,cls='',lazy=true)=>`<img ${cls?`class="${cls}"`:''} src="/assets/${name}.jpg" width="1672" height="941" ${lazy?'loading="lazy"':'fetchpriority="high"'} alt="${images[name]}">`;
function layout(title,desc,body,route='/',type='website',hero=null){
 const canonical=origin?`<link rel="canonical" href="${e(origin+route)}"><meta property="og:url" content="${e(origin+route)}">`:'';
 const social=origin&&hero?`<meta property="og:image" content="${e(origin)}/assets/${hero}.jpg"><meta property="og:image:alt" content="${e(images[hero])}; AI-generated style inspiration"><meta name="twitter:image" content="${e(origin)}/assets/${hero}.jpg">`:'';
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(title)} | ${brand}</title><meta name="description" content="${e(desc)}"><meta name="theme-color" content="#343f32"><meta property="og:title" content="${e(title)} | ${brand}"><meta property="og:description" content="${e(desc)}"><meta property="og:type" content="${type}"><meta property="og:site_name" content="${brand}"><meta name="twitter:card" content="${origin&&hero?'summary_large_image':'summary'}"><meta name="twitter:title" content="${e(title)} | ${brand}"><meta name="twitter:description" content="${e(desc)}">${canonical}${social}<link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/style.css"></head><body><a class="skip" href="#main">Skip to content</a><div class="announcement">A CONSIDERED HOME. AN EVERYDAY BUDGET.</div><header class="site-header"><div class="wrap header-inner"><a class="brand" href="/" aria-label="Linen and Form home">${logo}</a><nav aria-label="Main navigation">${nav}</nav><details class="mobile-menu"><summary>Menu</summary><nav aria-label="Mobile navigation">${nav}</nav></details></div></header><main id="main">${body}</main><footer class="site-footer"><div class="wrap"><div class="footer-top"><div><a class="brand" href="/">${logo}</a><p class="footer-desc">Beautifully considered. Sensibly chosen.</p></div><div class="footer-links"><a href="/about/">Our approach</a><a href="/contact/">Contact</a><a href="/privacy/">Privacy Policy</a><a href="/disclosure/">Affiliate disclosure</a></div></div><div class="disclosure"><p>${disclosure}</p><p>Unconfigured product slots are clearly marked. Room imagery is AI-generated style inspiration, not photography of linked products.</p><p>© 2026 ${brand}. Make room for what matters.</p></div></div></footer></body></html>`;
}
const readTime=a=>Math.max(2,Math.ceil([a.intro,a.takeaway,...a.sections.flatMap(s=>[s.title,...(s.paragraphs||[])]),...a.products.flatMap(p=>[p.name,p.why,p.check,p.skip])].join(' ').split(/\s+/).length/200));
const card=a=>`<article class="card"><a class="card-image" href="/guides/${a.slug}/" aria-hidden="true" tabindex="-1">${image(a.image)}</a><div class="card-meta">${e(a.category)} · ${readTime(a)} min read</div><h3><a href="/guides/${a.slug}/">${e(a.title)}</a></h3><p>${e(a.description)}</p><a class="read" href="/guides/${a.slug}/">Explore the guide<span class="sr-only">: ${e(a.title)}</span></a></article>`;
async function save(route,html){const dir=path.join(root,'public',route);await mkdir(dir,{recursive:true});await writeFile(path.join(dir,'index.html'),html);}
const home=`<div class="wrap"><section class="hero"><div><span class="eyebrow">The art of choosing well</span><h1>A little luxury.<br>A lot more<br><em>feeling at home.</em></h1><p>Thoughtful home finds and practical buying guides for beautiful rooms on an everyday budget.</p><a class="button" href="/guides/amazon-home-finds-look-expensive/">Explore the elevated home edit</a><p class="micro">Better proportions. Softer light. Pieces with a purpose.</p></div><figure class="hero-visual">${image('living','',false)}<div class="hero-stamp">An elevated home<br>starts with a good edit.</div></figure></section><nav class="topic-nav" aria-label="Explore by room"><a href="/guides/neutral-living-room-essentials/">Living room</a><a href="/guides/affordable-bedroom-upgrades/">Bedroom</a><a href="/guides/kitchen-upgrades-worth-buying/">Kitchen</a><a href="/guides/affordable-high-end-lighting/">Lighting</a><a href="/guides/vanity-beauty-organization/">Vanity & beauty</a><a href="/guides/apartment-essentials-worth-it/">Small spaces</a></nav><section class="section"><div class="section-heading"><div><span class="eyebrow">Start with your space</span><h2>Considered details.<br>Everyday difference.</h2></div><p>Find the texture, lighting, and useful finishing touches your room is missing.</p></div><div class="grid">${[articles[0],articles[1],articles[5]].map(card).join('')}</div></section><section class="feature">${image('bedroom')}<div class="feature-copy"><span class="eyebrow">The budget edit</span><h2>A smaller spend.<br>A more thoughtful space.</h2><p>Where to focus an under-$100 refresh, what to check before checkout, and when to keep what you already own.</p><a class="button" href="/guides/home-finds-under-100/">Read the under-$100 guide</a><p class="status">A budget framework, not a list of verified current prices.</p></div></section><section class="section"><div class="section-heading"><div><span class="eyebrow">Beautiful meets useful</span><h2>Make the everyday feel better.</h2></div><a href="/guides/">Browse all 10 guides</a></div><div class="grid">${[articles[4],articles[6],articles[3]].map(card).join('')}</div></section><section class="principles"><h2>Fewer impulse buys.<br>More things you love living with.</h2><p>We look at the whole decision: how a piece fits, what it does, and what to check before buying. Explore useful shopping criteria and clearly labeled product slots, without invented prices or claims of hands-on testing.</p></section></div>`;
await save('',layout('Affordable luxury home & apartment finds','Thoughtful home decor, furniture, bedroom, kitchen, lighting, and organization guides for an elevated home on an everyday budget.',home,'/','website','living'));
await save('guides',layout('Home & apartment buying guides','Ten thoughtful buying guides for home decor, furniture, lighting, bedroom upgrades, kitchen essentials, and small-space organization.',`<div class="wrap"><header class="guide-intro"><span class="eyebrow">The guide collection</span><h1>A more considered home,<br>one good choice at a time.</h1><p class="deck">Choose a room or a problem. Find practical selection advice, useful categories, and the details to check before you buy.</p></header><div class="grid all-guides section">${articles.map(card).join('')}</div></div>`,'/guides/','website','living'));
function product(p,i){const link=config.affiliateLinks[p.id];let cta='<span class="placeholder">Amazon affiliate link placeholder · coming after product selection</span>';if(link){const u=new URL(link);if(u.protocol!=='https:'||u.username||u.password||!(u.hostname==='amzn.to'||u.hostname==='amazon.com'||u.hostname.endsWith('.amazon.com')))throw Error(`Only HTTPS Amazon.com or amzn.to links allowed for ${p.id}`);cta=`<a class="button" href="${e(link)}" rel="sponsored nofollow noopener">View on Amazon <span>&nbsp;(paid link)</span></a>`;}return `<section class="product" id="${p.id}"><div class="product-number">${String(i+1).padStart(2,'0')}</div><div><span class="eyebrow">${link?'Our pick':'A category to consider'}</span><h3>${e(p.name)}</h3><p class="fit">${e(p.fit)}</p><p>${e(p.why)}</p><p class="checks"><strong>Before you buy:</strong> ${e(p.check)}</p><p><strong>When to skip it:</strong> ${e(p.skip)}</p>${cta}<small>${link?'Check the retailer’s current listing and complete cost before purchasing.':'No specific product, current price, or availability has been verified.'}</small></div></section>`;}
for(let i=0;i<articles.length;i++){
const a=articles[i];const sections=a.sections.map((s,j)=>`<section><h2 id="section-${j+1}">${e(s.title)}</h2>${s.paragraphs.map(p=>`<p>${e(p)}</p>`).join('')}</section>`).join('');
const body=`<div class="wrap"><div class="breadcrumb"><a href="/">Home</a> / <a href="/guides/">The guides</a> / ${e(a.category)}</div><header class="article-hero"><div><span class="eyebrow">${e(a.category)}</span><h1>${e(a.title)}</h1><p class="deck">${e(a.description)}</p><p class="meta">A ${brand} buying guide · ${readTime(a)} min read</p><a class="button" href="#the-edit">Explore the product categories</a></div><figure>${image(a.image,'',false)}<figcaption class="image-caption">AI-generated style inspiration. Pictured objects are not linked products.</figcaption></figure></header><div class="affiliate-note">${disclosure} We may earn a commission from purchases made through paid links. Unconfigured links are marked as placeholders. <a href="/disclosure/">How our links work</a>.</div><div class="article-layout"><article class="article-body"><p class="intro">${e(a.intro)}</p><div class="takeaway"><strong>The considered approach</strong><p>${e(a.takeaway)}</p></div><section><h2 id="the-edit">The pieces to consider</h2><p>Start with the category that solves a real problem in your space. These are selection guides, not tested product recommendations.</p><div class="shopping">${a.products.map(product).join('')}</div></section>${sections}${a.pins?`<section class="pin-it"><h2 id="save-this-guide">Save this guide for later</h2><p>Pin one of these to come back when you are ready to shop.</p><div class="pin-grid">${a.pins.map(p=>`<img src="${e(p.src)}" alt="${e(p.alt)}" width="1000" height="1500" loading="lazy">`).join('')}</div></section>`:''}<section><h2 id="final-check">Your final check before checkout</h2><p>Measure the space, verify the exact item’s specifications, and compare the complete price and return terms. Use what you already own if it does the job. A considered room comes together through fit and function, not the number of purchases.</p></section></article><aside class="sidebar" aria-label="In this guide"><div class="sidebar-inner"><strong>In this edit</strong><ol>${a.products.map(p=>`<li><a href="#${p.id}">${e(p.name)}</a></li>`).join('')}${a.sections.map((s,j)=>`<li><a href="#section-${j+1}">${e(s.title)}</a></li>`).join('')}<li><a href="#final-check">Before checkout</a></li></ol><div class="side-note takeaway"><strong>A useful rule</strong><p>Know its purpose.<br>Measure its place.<br>Check the details.</p></div></div></aside></div><section class="related"><span class="eyebrow">Continue the edit</span><h2>For the rest of your home.</h2><div class="grid section">${[articles[(i+1)%10],articles[(i+3)%10],articles[(i+6)%10]].map(card).join('')}</div></section></div>`;
await save(`guides/${a.slug}`,layout(a.title,a.description,body,`/guides/${a.slug}/`,'article',a.image));
}
const contactLink=email?`<a href="mailto:${e(email)}">${e(email)}</a>`:'<strong>Contact email not yet configured.</strong>';
const pages={
about:{title:'A home that feels considered.',description:'Meet Linen & Form: an editorial approach to affordable luxury home and apartment finds.',body:`<p class="deck">Beautifully considered. Sensibly chosen.</p><h2>What we believe</h2><p>An elevated home is not defined by its price tags. It is shaped by proportions that work, materials you like living with, and useful pieces chosen with care. ${brand} helps turn home inspiration into more thoughtful shopping decisions.</p><p>Our guides cover decor, furniture, bedroom upgrades, kitchen details, lighting, vanity organization, and the realities of smaller apartments. We focus on why a category might be useful, what to verify, and when to skip it.</p><h2>How our guides are made</h2><p>These starter guides offer original planning advice and product-selection criteria. They do not claim hands-on testing, personal ownership, guaranteed savings, or rankings based on tests. Product slots remain clearly marked until actual items and affiliate links are added.</p><p>We do not invent prices, reviews, ratings, retailer availability, or customer stories. Designer-inspired and high-end describe a visual direction, not an authenticated designer product or a guarantee of construction quality.</p><h2>About the imagery</h2><p>The room images are AI-generated style inspiration. They show an overall mood and arrangement, not specific products we have tested or items available through the links. Do not assume pictured objects correspond to a product selection.</p><h2>Useful before shoppable</h2><p>You can use the guides without buying anything. Measuring, rearranging, and using what you already own may be the best first step. If a purchase makes sense, verify the exact retailer listing and your own requirements before deciding.</p><p>For corrections or questions, <a href="/contact/">contact us</a>. ${config.ownerName?`Published by ${e(config.ownerName)}.`:''}</p>`},
contact:{title:'Let’s talk about your space.',description:'Contact Linen & Form with a question, guide correction, or topic suggestion.',body:`<p class="deck">A question, a correction, or an everyday home problem you would like us to cover?</p><h2>Email ${brand}</h2><p>${contactLink}</p><p>Please include the guide title and the specific passage if you are reporting an error. For a topic suggestion, tell us about the space and the decision you are trying to make.</p><h2>Orders and product support</h2><p>${brand} does not sell or ship products. Contact the retailer directly about payments, delivery, returns, warranties, or product support.</p><h2>Keep personal details private</h2><p>The email link opens your email application; it does not send a message automatically. Do not include passwords, payment details, or other sensitive information. Read our <a href="/privacy/">Privacy Policy</a> for information about contact messages.</p>`},
privacy:{title:'Privacy Policy',description:'How Linen & Form handles visitor information, contact emails, and external shopping links.',body:`<p class="status">Last updated: October 7, 2026</p><p>This policy describes ${brand} as currently configured. It applies to this website, not to retailers or other sites you visit through its links.</p><h2>Information on this website</h2><p>The site has no account system, newsletter signup, contact form, advertising pixels, or separate analytics service. Its own code does not set cookies or store browsing activity in local storage. The images and styling files are served with the website rather than loaded from a third-party image or font service.</p><h2>Hosting information</h2><p>The hosting provider may process technical request information such as IP address, browser details, requested URL, and request time to deliver the website, maintain security, and diagnose errors. When hosted on Vercel, its processing is described in the <a href="https://vercel.com/legal/privacy-policy" rel="noopener">Vercel Privacy Policy</a>.</p><h2>Email you choose to send</h2><p>If you email ${contactLink}, your address, message, and attachments are processed through Gmail so your request can be read and answered. Include only information needed for your request. Messages should be retained only as needed to handle correspondence and related records. You can contact us to request deletion of a message you sent.</p><h2>External and affiliate links</h2><p>Placeholder slots do not take you to a retailer. When affiliate links are configured, clicking a paid link takes you to an external site that may use cookies or other identifiers under its own policies to attribute a purchase. We do not receive your payment card information or process retailer transactions. Amazon’s handling is explained in its <a href="https://www.amazon.com/gp/help/customer/display.html?nodeId=GX7NJQ4ZB8MHFRNJ" rel="noopener">Privacy Notice</a>.</p><h2>Questions and changes</h2><p>Send privacy questions or requests to ${contactLink}. This policy will need updating if analytics, forms, mailing lists, advertising, or other data collection is added. The date above identifies the latest published revision.</p>`},
disclosure:{title:'Our affiliate disclosure',description:'How Linen & Form labels paid links, presents product categories, and distinguishes inspiration from verified products.',body:`<div class="takeaway"><strong>${disclosure}</strong></div><p>When an active affiliate link is used to make a qualifying purchase, ${brand} may receive a commission. Active paid links are labeled near the link so you can see the relationship before clicking.</p><h2>What the starter guides contain</h2><p>The guides describe product categories and buying criteria. Slots without a real affiliate URL remain non-clickable and clearly labeled as placeholders. They do not represent verified products, current availability, or a promise about price.</p><h2>Our approach to claims</h2><p>We do not claim hands-on testing of products in these guides. We do not publish invented reviews, star ratings, discounts, or prices. Affordable and luxury describe the site’s intended style and budget-conscious approach; value depends on the actual item and your needs.</p><p>The under-$100 guide uses a budget ceiling, not a list of verified current offers. Check the full cost, including required accessories, tax, and shipping, before purchasing.</p><h2>Inspiration and independence</h2><p>Room imagery is AI-generated inspiration and does not depict verified linked products. Affiliate participation does not mean Amazon sponsors or endorses ${brand}. You are welcome to use the advice without buying anything.</p><p>Questions about a link or a claim? <a href="/contact/">Contact us</a>.</p>`}
};
for(const [route,p]of Object.entries(pages))await save(route,layout(p.title,p.description,`<div class="wrap page"><span class="eyebrow">${brand}</span><h1>${p.title}</h1>${p.body}</div>`,`/${route}/`));
await writeFile(path.join(root,'public','404.html'),layout('Page not found','Find your way back to the Linen & Form guide collection.',`<div class="wrap page"><span class="eyebrow">404 · A little out of place</span><h1>Let’s find your way home.</h1><p>This page may have moved. Explore our home and apartment guides to find what you need.</p><a class="button" href="/guides/">Explore the guides</a></div>`));
const routes=['/','/guides/',...articles.map(a=>`/guides/${a.slug}/`),...Object.keys(pages).map(p=>`/${p}/`)];
await writeFile(path.join(root,'public','robots.txt'),`User-agent: *\nAllow: /\n${origin?`Sitemap: ${origin}/sitemap.xml\n`:''}`);
await writeFile(path.join(root,'public','sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${origin?routes.map(r=>`<url><loc>${e(origin+r)}</loc></url>`).join(''):''}</urlset>`);
console.log(`Built ${routes.length} Linen & Form pages plus 404. ${origin?'Canonical URLs, social image URLs, and sitemap configured.':'Set site.json url to enable canonical URLs, social image URLs, and sitemap entries.'}`);
